version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for swift package manager
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "daily"

