coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.1%
ignore:
  - "**/*Tests.swift"
  - "Tests/**"
  - "**/TestSupport/**"
  - "**/Test Support/**"
  - "**/Testing Support/**"
  - "**/*.xctest/**"
