//
/*
Copyright 2025 Splunk Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

import Foundation
import SplunkCommon


/// A placeholder type for AppStart module event data.
///
/// This empty structure is used to signal events that do not carry a specific payload.
public struct AppStartData: ModuleEventData {}

/// A structure that provides metadata for events generated by the AppStart module.
public struct AppStartMetadata: ModuleEventMetadata {
    /// The timestamp indicating when the event occurred.
    public var timestamp = Date()
}

/// Extends `AppStart` to conform to the `Module` protocol, enabling its integration within the agent framework.
extension AppStart: Module {

    // MARK: - Module types

    public typealias Configuration = AppStartConfiguration
    public typealias RemoteConfiguration = AppStartRemoteConfiguration
    public typealias EventMetadata = AppStartMetadata
    public typealias EventData = AppStartData


    // MARK: - Module methods

    /// Installs the AppStart module and begins detecting application start events.
    ///
    /// This method is called during the agent's initialization to activate the module.
    /// - Parameters:
    ///   - configuration: The local configuration for the module. This parameter is currently unused.
    ///   - remoteConfiguration: The remote configuration for the module. This parameter is currently unused.
    public func install(with configuration: (any ModuleConfiguration)?, remoteConfiguration: (any RemoteModuleConfiguration)?) {
        startDetection()
    }


    // MARK: - Type transparency helpers

    /// A placeholder for handling the deletion of data associated with a specific event.
    ///
    /// - Note: This method is a no-op as the AppStart module does not persist data that requires explicit deletion.
    /// - Parameter metadata: The metadata of the event whose data should be deleted.
    public func deleteData(for metadata: any ModuleEventMetadata) {}

    /// A placeholder for registering a callback to publish AppStart event data.
    ///
    /// - Note: This method is a no-op because the AppStart module reports data directly through the OTel pipeline
    /// rather than publishing it through a callback mechanism.
    /// - Parameter data: A closure to be called when new event data is available.
    public func onPublish(data: @escaping (AppStartMetadata, AppStartData) -> Void) {}
}
