#!/bin/bash
# tools/xcframework/scripts/build-xcframeworks.sh
#
# Builds all SplunkAgent module xcframeworks using the Tuist-generated
# Xcode project. Archives each scheme for each platform in its platform
# matrix, then creates xcframeworks from the archives.
#
# Usage:
#   ./scripts/build-xcframeworks.sh [--ios-only]
#
# Environment variables:
#   IOS_ONLY - When true, build only iOS device and simulator slices
#
# Prerequisites:
#   - `tuist generate` has been run (or will be run by this script)
#   - dependencies/ directory is populated with pre-built xcframeworks
#   - Xcode 16+ with command-line tools
#
# Output:
#   output/xcframeworks/<ModuleName>.xcframework for each module

set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOLS_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

BUILD_DIR="${TOOLS_ROOT}/build/agent"
ARCHIVES_DIR="${BUILD_DIR}/archives"
OUTPUT_DIR="${TOOLS_ROOT}/output/xcframeworks"

CONFIGURATION="Release"
IOS_ONLY="${IOS_ONLY:-false}"

# Workspace generated by Tuist
WORKSPACE="${TOOLS_ROOT}/SplunkAgentXCFrameworks.xcworkspace"


# ---------------------------------------------------------------------------
# Platform Definitions
# ---------------------------------------------------------------------------

# All platforms (7 destinations)
ALL_PLATFORMS=(
    "ios|generic/platform=iOS"
    "ios-simulator|generic/platform=iOS Simulator"
    "tvos|generic/platform=tvOS"
    "tvos-simulator|generic/platform=tvOS Simulator"
    "xros|generic/platform=visionOS"
    "xros-simulator|generic/platform=visionOS Simulator"
    "maccatalyst|generic/platform=macOS,variant=Mac Catalyst"
)

# Platforms excluding visionOS (5 destinations)
# Used for SplunkCrashReports (PLCrashReporter does not support visionOS)
NO_VISIONOS_PLATFORMS=(
    "ios|generic/platform=iOS"
    "ios-simulator|generic/platform=iOS Simulator"
    "tvos|generic/platform=tvOS"
    "tvos-simulator|generic/platform=tvOS Simulator"
    "maccatalyst|generic/platform=macOS,variant=Mac Catalyst"
)

IOS_PLATFORMS=(
    "ios|generic/platform=iOS"
    "ios-simulator|generic/platform=iOS Simulator"
)


# ---------------------------------------------------------------------------
# Module Definitions
# ---------------------------------------------------------------------------
# Each module with its platform matrix. Order matters: dependencies first.
# Format: "scheme_name|platform_array_name"
#
# Build order follows the dependency graph:
#   1. SplunkCommon (foundation for all)
#   2. Standalone modules (depend on SplunkCommon + externals)
#   3. SplunkOpenTelemetryBackgroundExporter (depends on SplunkCommon)
#   4. SplunkOpenTelemetry (depends on BackgroundExporter)
#   5. SplunkCustomTracking (depends on SplunkOpenTelemetry)
#   6. SplunkAgent (depends on everything)
#   7. SplunkAgentObjC (depends on SplunkAgent)

# Build order (dependencies first) and platform matrix.
# SplunkCrashReports uses NO_VISIONOS; all others use ALL.
BUILD_ORDER=(
    SplunkCommon
    SplunkNavigation
    SplunkNetwork
    SplunkNetworkMonitor
    SplunkSlowFrameDetector
    SplunkCrashReports
    SplunkOpenTelemetryBackgroundExporter
    SplunkOpenTelemetry
    SplunkInteractions
    SplunkAppStart
    SplunkAppState
    SplunkWebView
    SplunkCustomTracking
    SplunkSessionReplayProxy
    SplunkAgent
    SplunkAgentObjC
)

# Modules that use restricted platforms (no visionOS).
# All modules NOT listed here use ALL_PLATFORMS.
NO_VISIONOS_MODULES="SplunkCrashReports"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

log() {
    echo "==> $*"
}

log_step() {
    echo ""
    echo "============================================================"
    echo "  $*"
    echo "============================================================"
}

platform_label() {
    echo "$1" | cut -d'|' -f1
}

platform_destination() {
    echo "$1" | cut -d'|' -f2
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --ios-only)
            IOS_ONLY=true
            shift
            ;;
        *)
            echo "Unknown argument: $1"
            exit 1
            ;;
    esac
done

# Returns the platform entries for a given module, one per line.
# Uses string matching (bash 3.2 compatible, no associative arrays).
get_platforms() {
    local module="$1"
    local entries

    if [[ "${IOS_ONLY}" == "true" ]]; then
        entries=("${IOS_PLATFORMS[@]}")
        printf '%s\n' "${entries[@]}"
        return
    fi

    # Check if module is in the no-visionOS list
    case " ${NO_VISIONOS_MODULES} " in
        *" ${module} "*)
            entries=("${NO_VISIONOS_PLATFORMS[@]}")
            ;;
        *)
            entries=("${ALL_PLATFORMS[@]}")
            ;;
    esac

    # Print one entry per line to avoid space-splitting issues
    # (destinations contain spaces, e.g. "generic/platform=iOS Simulator")
    printf '%s\n' "${entries[@]}"
}


# ---------------------------------------------------------------------------
# Step 1: Generate Xcode project
# ---------------------------------------------------------------------------

generate_project() {
    log_step "Step 1: Generate Xcode project with Tuist"

    cd "${TOOLS_ROOT}"

    if [[ ! -d "${WORKSPACE}" ]]; then
        tuist generate --no-open

        # Fix deprecated build settings injected by Tuist
        "${SCRIPT_DIR}/fix-tuist-warnings.sh" "${TOOLS_ROOT}/SplunkAgentXCFrameworks.xcodeproj"

        log "Workspace generated"
    else
        log "Workspace already exists, skipping generation"
        log "  (run 'make clean' and rebuild to regenerate)"
    fi
}


# ---------------------------------------------------------------------------
# Step 2: Archive each module for each platform
# ---------------------------------------------------------------------------

archive_module() {
    local scheme="$1"

    while IFS= read -r platform_entry; do
        [[ -z "${platform_entry}" ]] && continue
        local label
        label="$(platform_label "${platform_entry}")"
        local destination
        destination="$(platform_destination "${platform_entry}")"
        local archive_path="${ARCHIVES_DIR}/${scheme}-${label}.xcarchive"

        # Skip if archive already exists (incremental builds)
        if [[ -d "${archive_path}" ]]; then
            echo "  ⏩ ${scheme}-${label} (cached)"
            continue
        fi

        echo "  📦 ${scheme} → ${label}..."

        # Cisco Session Replay xcframeworks ship arm64-only macCatalyst
        # slices, so we must restrict macCatalyst builds to arm64 to
        # avoid "unsupported Swift architecture" errors on x86_64.
        local xcodebuild_args=(
            archive
            -workspace "${WORKSPACE}"
            -scheme "${scheme}"
            -configuration "${CONFIGURATION}"
            -destination "${destination}"
            -archivePath "${archive_path}"
            SKIP_INSTALL=NO
            BUILD_LIBRARY_FOR_DISTRIBUTION=YES
        )
        if [[ "${label}" == "maccatalyst" ]]; then
            xcodebuild_args+=("ARCHS=arm64")
            xcodebuild_args+=("IPHONEOS_DEPLOYMENT_TARGET=15.0")
        fi

        xcodebuild "${xcodebuild_args[@]}" 2>&1 | tail -3

        if [[ ! -d "${archive_path}" ]]; then
            echo "ERROR: Archive failed for ${scheme} (${label})"
            exit 1
        fi
    done < <(get_platforms "${scheme}")
}

archive_all() {
    if [[ "${IOS_ONLY}" == "true" ]]; then
        log_step "Step 2: Archive modules for iOS platforms"
    else
        log_step "Step 2: Archive modules for all platforms"
    fi

    mkdir -p "${ARCHIVES_DIR}"

    for scheme in "${BUILD_ORDER[@]}"; do
        log "Archiving ${scheme}..."
        archive_module "${scheme}"
    done
}


# ---------------------------------------------------------------------------
# Step 3: Create xcframeworks
# ---------------------------------------------------------------------------

create_xcframework() {
    local scheme="$1"
    local xcframework_path="${OUTPUT_DIR}/${scheme}.xcframework"

    # Remove existing
    rm -rf "${xcframework_path}"

    local create_args=()

    while IFS= read -r platform_entry; do
        [[ -z "${platform_entry}" ]] && continue
        local label
        label="$(platform_label "${platform_entry}")"
        local archive_path="${ARCHIVES_DIR}/${scheme}-${label}.xcarchive"
        local framework_path="${archive_path}/Products/Library/Frameworks/${scheme}.framework"

        if [[ ! -d "${framework_path}" ]]; then
            echo "ERROR: Framework not found at ${framework_path}"
            exit 1
        fi

        create_args+=(-framework "${framework_path}")

        # Include dSYMs if present
        local dsym_path="${archive_path}/dSYMs/${scheme}.framework.dSYM"
        if [[ -d "${dsym_path}" ]]; then
            create_args+=(-debug-symbols "${dsym_path}")
        fi
    done < <(get_platforms "${scheme}")

    xcodebuild -create-xcframework \
        "${create_args[@]}" \
        -output "${xcframework_path}" 2>&1 | tail -2

    if [[ ! -d "${xcframework_path}" ]]; then
        echo "ERROR: Failed to create ${scheme}.xcframework"
        exit 1
    fi

    echo "  ✓ ${scheme}.xcframework"
}

create_all_xcframeworks() {
    log_step "Step 3: Create xcframeworks"

    mkdir -p "${OUTPUT_DIR}"

    for scheme in "${BUILD_ORDER[@]}"; do
        create_xcframework "${scheme}"
    done
}


# ---------------------------------------------------------------------------
# Step 4: Summary
# ---------------------------------------------------------------------------

print_summary() {
    log_step "Build complete"

    echo "XCFrameworks built:"
    for scheme in "${BUILD_ORDER[@]}"; do
        local path="${OUTPUT_DIR}/${scheme}.xcframework"
        if [[ -d "${path}" ]]; then
            local size
            size="$(du -sh "${path}" 2>/dev/null | cut -f1)"
            echo "  ✓ ${scheme}.xcframework (${size})"
        else
            echo "  ✗ ${scheme}.xcframework (MISSING)"
        fi
    done
}


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

main() {
    log "Building SplunkAgent xcframeworks"
    log "iOS-only: ${IOS_ONLY}"

    generate_project
    archive_all
    create_all_xcframeworks
    print_summary
}

main "$@"
