name: "Build & Tests"
description: "Ensures Agent can build and tests are working."
author: "Filip Ruzicka (fruzicka@splunk.com)"

on:
  workflow_call:
    outputs:
      scheme:
        value: ${{ jobs.build_and_test.outputs.scheme }}
      build_matrix:
        value: ${{ jobs.build_and_test.outputs.build_matrix }}
      test_matrix:
        value: ${{ jobs.build_and_test.outputs.test_matrix }}
      test_status:
        value: ${{ jobs.build_and_test.outputs.test_status }}
jobs:
  prepare:
    runs-on: macos-latest
    outputs:
      scheme: ${{ steps.scheme.outputs.scheme }}
      build_matrix: ${{ steps.dest.outputs.build_matrix }}
      test_matrix: ${{ steps.dest.outputs.test_matrix }}
    steps:
      - checkout
      - setup-xcode
      - run: ./scripts/prepare-workspace.sh
      - id: scheme
        run: ./scripts/prepare-scheme.sh
      - id: dest
        env:
          SCHEME: ${{ steps.scheme.outputs.scheme }}
        run: ./scripts/resolve-destinations.sh

  build:
    needs: prepare
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.build_matrix) }}
    steps:
      - checkout
      - setup-xcode
      - run: SCHEME=${{ needs.prepare.outputs.scheme }} DESTINATION=${{ matrix.destination }} ./scripts/build.sh

  tests:
    needs: prepare
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.test_matrix) }}
    steps:
      - checkout
      - setup-xcode
      - run: SCHEME=${{ needs.prepare.outputs.scheme }} DESTINATION=${{ matrix.destination }} ./scripts/test.sh
