name: "Build & Tests"
description: "Ensures Agent can build and tests are working."
author: "Filip Ruzicka (fruzicka@splunk.com)"

on:
  workflow_call:

jobs:
  prepare:
    runs-on: macos-latest
    outputs:
      scheme: ${{ steps.scheme.outputs.scheme }}
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - run: chmod +x .github/actions/build-and-tests/scripts/*.sh
      - run: .github/actions/build-and-tests/scripts/neutralize-sdk.sh
      - run: .github/actions/build-and-tests/scripts/prepare-workspace.sh
      - id: scheme
        run: .github/actions/build-and-tests/scripts/prepare-scheme.sh

  build:
    runs-on: macos-latest
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ios
          - platform: tvos
          - platform: visionos
          - platform: macCatalyst
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - run: chmod +x .github/actions/build-and-tests/scripts/*.sh
      - run: .github/actions/build-and-tests/scripts/neutralize-sdk.sh
      - run: .github/actions/build-and-tests/scripts/prepare-workspace.sh
      - name: Resolve destination for ${{ matrix.platform }}
        id: resolve
        env:
          SCHEME: ${{ needs.prepare.outputs.scheme }}
          PLATFORM: ${{ matrix.platform }}
        run: .github/actions/build-and-tests/scripts/resolve-destination-for-platform.sh
      - name: Ensure destination is installed
        env:
          DEST: ${{ env.DEST }}
        run: .github/actions/build-and-tests/scripts/ensure-destination.sh
      - name: Build ${{ matrix.platform }}
        env:
          SCHEME: ${{ needs.prepare.outputs.scheme }}
          DESTINATION: ${{ env.DEST }}
        run: .github/actions/build-and-tests/scripts/build.sh

  tests:
    runs-on: macos-latest
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ios
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - run: chmod +x .github/actions/build-and-tests/scripts/*.sh
      - run: .github/actions/build-and-tests/scripts/neutralize-sdk.sh
      - run: .github/actions/build-and-tests/scripts/prepare-workspace.sh
      - name: Resolve destination for ${{ matrix.platform }}
        id: resolve
        env:
          SCHEME: ${{ needs.prepare.outputs.scheme }}
          PLATFORM: ${{ matrix.platform }}
        run: .github/actions/build-and-tests/scripts/resolve-destination-for-platform.sh
      - name: Ensure destination is installed
        env:
          DEST: ${{ env.DEST }}
        run: .github/actions/build-and-tests/scripts/ensure-destination.sh
      - id: run
        env:
          SCHEME: ${{ needs.prepare.outputs.scheme }}
          DESTINATION: ${{ env.DEST }}
          PLATFORM: ${{ matrix.platform }}
        run: |
          export GITHUB_OUTPUT="$(mktemp)"
          .github/actions/build-and-tests/scripts/test.sh
          code="$(sed -n 's/^xcode_status=//p' "$GITHUB_OUTPUT")"
          echo "status=${code:-1}" >> "$GITHUB_OUTPUT"
      - uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: reports/junit-${{ matrix.platform }}.xml
          check_name: Tests (${{ matrix.platform }})
          require_tests: true
          include_passed: true
          fail_on_failure: false
          detailed_summary: true
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: TestResults_${{ matrix.platform }}.xcresult
          path: TestResults_${{ matrix.platform }}.xcresult
          if-no-files-found: warn
