name: "Build & Tests"
description: "Ensures Agent can build and tests are working."
author: "Filip Ruzicka (fruzicka@splunk.com)"

on:
  workflow_call:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ios
          - platform: tvos
          - platform: visionos
          - platform: macCatalyst
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - run: chmod +x .github/actions/build-and-tests/scripts/*.sh

      - name: Prepare workspace
        run: |
          .github/actions/build-and-tests/scripts/neutralize-sdk.sh
          .github/actions/build-and-tests/scripts/prepare-workspace.sh

      - name: Resolve scheme
        id: scheme
        run: .github/actions/build-and-tests/scripts/prepare-scheme.sh

      - name: Resolve destinations
        id: dest
        run: .github/actions/build-and-tests/scripts/resolve-destinations.sh

      - name: Select destination for ${{ matrix.platform }}
        run: |
          case "${{ matrix.platform }}" in
            ios) echo "DEST=${{ steps.dest.outputs.ios_build_dest }}" >> "$GITHUB_ENV" ;;
            tvos) echo "DEST=${{ steps.dest.outputs.tvos_build_dest }}" >> "$GITHUB_ENV" ;;
            visionos) echo "DEST=${{ steps.dest.outputs.visionos_build_dest }}" >> "$GITHUB_ENV" ;;
            macCatalyst) echo "DEST=${{ steps.dest.outputs.maccatalyst_dest }}" >> "$GITHUB_ENV" ;;
          esac
          echo "Platform=${{ matrix.platform }}"
          echo "Destination=$DEST"

      - name: Build ${{ matrix.platform }}
        env:
          SCHEME: ${{ steps.scheme.outputs.scheme }}
          DESTINATION: ${{ env.DEST }}
        run: .github/actions/build-and-tests/scripts/build.sh

  tests:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ios
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - run: chmod +x .github/actions/build-and-tests/scripts/*.sh

      - name: Prepare workspace
        run: |
          .github/actions/build-and-tests/scripts/neutralize-sdk.sh
          .github/actions/build-and-tests/scripts/prepare-workspace.sh

      - name: Resolve scheme
        id: scheme
        run: .github/actions/build-and-tests/scripts/prepare-scheme.sh

      - name: Resolve destinations
        id: dest
        run: .github/actions/build-and-tests/scripts/resolve-destinations.sh

      - name: Select destination for ${{ matrix.platform }}
        run: |
          case "${{ matrix.platform }}" in
            ios) echo "DEST=${{ steps.dest.outputs.ios_dest }}" >> "$GITHUB_ENV" ;;
            tvos) echo "DEST=${{ steps.dest.outputs.tvos_dest }}" >> "$GITHUB_ENV" ;;
            visionos) echo "DEST=${{ steps.dest.outputs.visionos_dest }}" >> "$GITHUB_ENV" ;;
            macCatalyst) echo "DEST=${{ steps.dest.outputs.maccatalyst_dest }}" >> "$GITHUB_ENV" ;;
          esac
          echo "Platform=${{ matrix.platform }}"
          echo "Destination=$DEST"

      - id: run
        env:
          SCHEME: ${{ steps.scheme.outputs.scheme }}
          DESTINATION: ${{ env.DEST }}
        run: |
          export GITHUB_OUTPUT="$(mktemp)"
          .github/actions/build-and-tests/scripts/test.sh
          code="$(sed -n 's/^xcode_status=//p' "$GITHUB_OUTPUT")"
          echo "status=${code:-1}" >> "$GITHUB_OUTPUT"
      - uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: reports/junit-${{ matrix.platform }}.xml
          check_name: Tests (${{ matrix.platform }})
          require_tests: true
          include_passed: true
          fail_on_failure: false
          detailed_summary: true
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: TestResults_${{ matrix.platform }}.xcresult
          path: TestResults_${{ matrix.platform }}.xcresult
          if-no-files-found: warn
