name: "Build & Tests"
description: "Ensures Agent can build and tests are working."
author: "Filip Ruzicka (fruzicka@splunk.com)"

runs:
  using: "composite"
  steps:
    - name: Build 
      shell: bash
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}
        PR_AUTHOR: ${{ github.event.pull_request.user.login }}
      run: bash ./.github/actions/validate-pr-title/pr_title_check.sh
