//
/*
Copyright 2025 Splunk Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

import Foundation

/// A data structure that holds metadata for events generated by the `SlowFrameDetector`.
///
/// This metadata is used to uniquely identify and timestamp each event, conforming to the `ModuleEventMetadata` protocol.
public struct EventMetadataSlowFrameDetector {

    // MARK: - Public

    /// The timestamp indicating when the event occurred.
    public var timestamp = Date()

    // MARK: - Internal

    let id: String
}
