//
/*
Copyright 2025 Splunk Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

import Foundation
import SplunkCommon

/// A placeholder type for Network Instrumentation module event data.
///
/// This empty structure is used to signal events that do not carry a specific payload.
public struct NetworkInstrumentationData: ModuleEventData {}

/// A structure that provides metadata for events generated by the Network Instrumentation module.
public struct NetworkInstrumentationMetadata: ModuleEventMetadata {
    /// The timestamp indicating when the event occurred.
    public var timestamp = Date()
}

/// Extends `NetworkInstrumentation` to conform to the `Module` protocol, enabling its integration within the agent framework.
extension NetworkInstrumentation: Module {

    // MARK: - Module types

    /// The type used for local configuration of the Network Instrumentation module.
    public typealias Configuration = NetworkInstrumentationConfiguration
    /// The type used for remote configuration of the Network Instrumentation module.
    public typealias RemoteConfiguration = NetworkInstrumentationRemoteConfig

    /// The metadata type for events generated by the Network Instrumentation module.
    public typealias EventMetadata = NetworkInstrumentationMetadata
    /// The data payload type for events generated by the Network Instrumentation module.
    public typealias EventData = NetworkInstrumentationData

    // MARK: - Type transparency helpers

    // An empty implementation as the module publishes data internally through the OTel trace exporter SDK.
    public func onPublish(data: @escaping (NetworkInstrumentationMetadata, NetworkInstrumentationData) -> Void) {}

    // An empty implementation as the module does not store any data.
    public func deleteData(for metadata: any ModuleEventMetadata) {}
}
