//
/*
Copyright 2025 Splunk Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

import Foundation
import SplunkCommon

// `String` can be used as an event type that the module produces.
// This is due to the fact the Crash Reports module serializes
// the whole Crash payload JSON in place to `String`.
extension String: ModuleEventData {}

/// Describes the Crash Report event metadata.
public struct CrashReportsMetadata: ModuleEventMetadata {
    /// The timestamp indicating when the crash event was processed.
    public var timestamp = Date()
    /// The name of the event, which is always "device.app.crash".
    public var eventName: String = "device.app.crash"
}

/// Extends `CrashReports` to conform to the `Module` protocol, enabling its integration within the agent framework.
extension CrashReports: Module {


    // MARK: - Module types

    /// The type used for local configuration of the Crash Reports module.
    public typealias Configuration = CrashReportsConfiguration
    /// The type used for remote configuration of the Crash Reports module.
    public typealias RemoteConfiguration = CrashReportsRemoteConfiguration

    /// The metadata type for events generated by the Crash Reports module.
    public typealias EventMetadata = CrashReportsMetadata
    /// The data payload type for events, which is a `String` containing the serialized crash report.
    public typealias EventData = String


    // MARK: - Module methods

    /// Installs and configures the Crash Reports module.
    ///
    /// This method sets up the underlying `PLCrashReporter` and enables it if the configuration specifies.
    /// - Parameters:
    ///   - configuration: The local configuration, which determines if the module is enabled.
    ///   - remoteConfiguration: The remote configuration. This parameter is currently unused.
    public func install(with configuration: (any SplunkCommon.ModuleConfiguration)?, remoteConfiguration: (any SplunkCommon.RemoteModuleConfiguration)?) {

        // Configure PLCrashReporter
        configureCrashReporter()

        // Start the crash reporter if it's enabled or if no configuration is provided.
        let config = configuration as? Configuration
        if config?.isEnabled ?? true {
            _ = initializeCrashReporter()
        }
    }


    // MARK: - Module event data publishing

    /// Registers a callback to consume crash report data.
    ///
    /// The provided block will be invoked when a crash report is processed and ready for publishing.
    /// - Parameter block: A closure that takes `CrashReportsMetadata` and a `String` (the crash report) as arguments.
    public func onPublish(data block: @escaping (CrashReportsMetadata, String) -> Void) {
       crashReportDataConsumer = block
    }

    // An empty implementation as the purging of the actual crash report data
    // is handled by the PL Crash Reporter internally.
    /// A placeholder for handling the deletion of data associated with a specific event.
    ///
    /// - Note: This method is a no-op because the underlying `PLCrashReporter` framework manages the lifecycle
    /// of crash report files, including their deletion after processing.
    /// - Parameter metadata: The metadata of the event whose data should be deleted.
    public func deleteData(for metadata: any ModuleEventMetadata) {}
}
