//
/*
Copyright 2025 Splunk Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

import Foundation
import SplunkCommon

/// A placeholder type for Network Monitor module event data.
///
/// This empty structure is used to signal events that do not carry a specific payload.
public struct NetworkMonitorData: ModuleEventData {}

/// A structure that provides metadata for events generated by the Network Monitor module.
public struct NetworkMonitorMetadata: ModuleEventMetadata {
    /// The timestamp indicating when the network change event occurred.
    public var timestamp = Date()
    /// The name of the event, which is always "network.change".
    public var eventName: String = "network.change"
}

/// Extends `NetworkMonitor` to conform to the `Module` protocol, enabling its integration within the agent framework.
extension NetworkMonitor: Module {

    // MARK: - Module types

    public typealias Configuration = NetworkMonitorConfiguration
    public typealias RemoteConfiguration = NetworkMonitorRemoteConfiguration
    public typealias EventMetadata = NetworkMonitorMetadata
    public typealias EventData = NetworkMonitorData


    // MARK: - Module methods

    /// Installs the Network Monitor module and begins detecting network changes.
    ///
    /// This method is called during the agent's initialization to activate the module. It starts network
    /// detection if the module is enabled in the provided configuration.
    /// - Parameters:
    ///   - configuration: The local configuration, which determines if the module is enabled.
    ///   - remoteConfiguration: The remote configuration. This parameter is currently unused.
    public func install(with configuration: (any ModuleConfiguration)?, remoteConfiguration: (any RemoteModuleConfiguration)?) {
        let config = configuration as? Configuration

        // Start the network monitor if it's enabled or if no configuration is provided.
        if config?.isEnabled ?? true {
            startDetection()
        }
    }


    // MARK: - Type transparency helpers

    /// A placeholder for handling the deletion of data associated with a specific event.
    ///
    /// - Note: This method is a no-op as the Network Monitor module does not persist data that requires explicit deletion.
    /// - Parameter metadata: The metadata of the event whose data should be deleted.
    public func deleteData(for metadata: any ModuleEventMetadata) {}

    /// A placeholder for registering a callback to publish network change event data.
    ///
    /// - Note: This method is a no-op because the Network Monitor module reports data directly through the OTel pipeline
    /// as spans rather than publishing it through a callback mechanism.
    /// - Parameter data: A closure to be called when new event data is available.
    public func onPublish(data: @escaping (NetworkMonitorMetadata, NetworkMonitorData) -> Void) {}
}
