name: Continuous Integration
on:
  push:
    branches: [ "feature/next-gen" ]
  pull_request:
    branches: [ "feature/next-gen" ]

jobs:
  # build:
  #   runs-on: macos-14
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
  #     - name: Build
  #       run: ./Tools/build_frameworks.sh
  #     - name: Upload coverage to Codecov
  #       uses: codecov/codecov-action@a079530fc142d3d288ddf76321ca0b7fe5b18df5 # v4.4.1
  check_links:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
      - name: Link Checker
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2.9.0
        with:
          fail: true
